version: '1.0'

services:
  substrate-contracts-node:
    build:
      context: .
      dockerfile: Dockerfile
    image: contracts-node:latest
    container_name: substrate-contracts-node
    ports:
      - "9944:9944"